### ISSUE TITLE
Repo in Fedora 25

### ISSUE THREAD

**Issue by arquio** [TomasTomecek/fedora_rpm_xmind#7]
Step1: ok

> sudo dnf copr enable ttomecek/xmind

Step 2: Fail

> $ sudo dnf install -y xmind
> Failed to synchronize cache for repo 'ttomecek-xmind', disabling.
> Last metadata expiration check: 0:06:59 ago on Thu Dec  1 18:16:17 2016.
> No package xmind available.
> Error: Unable to find a match.

Thank u!

**Comment by TomasTomecek** [comment]
Good point. Here you go: https://copr.fedorainfracloud.org/coprs/ttomecek/xmind/build/483962/
